### ISSUE TITLE
Add WP menu to footer instead of hard-coding nav link

### ISSUE THREAD

**Issue by mandiwise** [redacademy/spirit-winter-2017#5]
At the top of the footer you have a list of nav links that should actually be built out as secondary menu on the site. Please remove the hard-coded list of links, register a new nav menu in functions.php, and add a the menu template tag to your footer.php.

After you do that, please build out this menu using the WP admin UI instead.

**Comment by ShirleyDenise** [comment]
https://github.com/redacademy/spirit-winter-2017/commit/7ff2e12cc4bec80ce7b643c1d89775716c9c4132
