### ISSUE TITLE
Buttons should be buttons, links should be links

### ISSUE THREAD

**Issue by mandiwise** [redacademy/spirit-winter-2017#9]
If something can be click on but it doesn't actually navigate the user elsewhere on the site, it should be a button.

For example, this:

```
<a href="" class="blue-btn">Learn More</a>
```

Should be this:

```
<button class="blue-btn">Learn More</button>
```

**Comment by redm17** [comment]
These anchor tags will all be functional links. Will close issue once URLs are added.
